spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hotel_management_test?serverTimezone=UTC
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 300114743744-70nk0k5edga6uc3v1uilf6nq1dod9ten.apps.googleusercontent.com
            client-secret: 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
          facebook:
            clientId: 1188065051720022
            clientSecret: 40d74f69d47ba8c75a59569232845999
         
          